### ISSUE TITLE
React.Suspense only renders the first child in Enzyme.

### ISSUE THREAD

**Issue by cnzh2992** [wojtekmaj/enzyme-adapter-react-17#34]
Hi, I tried to test on a component with multiple children wrapped in `<Suspense />`, like:

```
<Suspense fallback={...}>
  <div />
  <div />
  <div />
</Suspense>
```

Only the first `div` rendered in test framework.

Here's the [reproduction link](https://codesandbox.io/s/suspense-multiple-children-yw7oe?file=/src/Suspense.js). It looks good on browser and React Testing Framework but failed on Enzyme. Is it a bug of React 17 adapter?

**Comment by wojtekmaj** [comment]
Looks like a bug indeed.

Note to self: Might be related to https://github.com/enzymejs/enzyme/pull/2430#issuecomment-718957496
