### ISSUE TITLE
Update to React 17.0.2

### ISSUE THREAD

**Issue by martin-badin** [wojtekmaj/enzyme-adapter-react-17#41]
Hi guys.

Could someone add support for React 17.0.2?

**Comment by wojtekmaj** [comment]
It's supported.

**Comment by hugobarragon** [comment]
hi @wojtekmaj  , plz consider opening this, this is a issue, on the peer deps you should remove the `-0` on each dep and chagne to the following pattern:    
https://nodejs.org/es/blog/npm/peer-dependencies/  
```
"peerDependencies": {
    "enzyme": ">= 3.0.0",
    "react": ">= 17.0.0",
    "react-dom": ">= 17.0.0"
  },
``` 
  
![image](https://user-images.githubusercontent.com/35630927/151006590-eb4630c7-4b68-4ecb-a0ee-113aee17dcd4.png)

**Comment by wojtekmaj** [comment]
@hugobarragon Is that Yarn v1?

17.0.0-0 should definitely match 17.0.2 as well.

Removing the -0 bit removes support for prereleases, betas and so on and would be considered a breaking change
