### ISSUE TITLE
Any change in the Type "@types/enzyme-adapter-react-16"?

### ISSUE THREAD

**Issue by naminder** [wojtekmaj/enzyme-adapter-react-17#5]

**Comment by wojtekmaj** [comment]
Not sure. @noah-friedman was the author of types for this package, later corrected by @mmarcuccio.

**Comment by mmarcuccio** [comment]
@naminder I don't fully understand the question - do you mind elaborating?
This package ships its own types. You don't need to use a package from definitely typed.
@types/enzyme-adapter-react-16 provides types for the official enzyme-adapter-react-16 package only and is unrelated to @wojtekmaj/enzyme-adapter-react-17.

**Comment by naminder** [comment]
@mmarcuccio you are right,

In React 16x, we use adapter-16 with @types/enzyme-adapter-react-16.

If I am migrating to React 17, I will use adapter 17.

So my question is for the types package do I need to update that as well or the same type would work, if my project is using typescript.

So I just gave it a try right now, and it seems it is working fine with current latest version of @types/enzyme-adapter-react-16. Which means no change required in types package.

I would like to appreciate the fact you guys went ahead and built to so developers could migrate to 17x, and thanks a lot for this package. 👍 and are so good and quick in responding.

**Comment by wojtekmaj** [comment]
Thanks guys for helping me with that one :)
