### ISSUE TITLE
Conflicting peer dependency `react@"^17.0.0-0"`

### ISSUE THREAD

**Issue by k-funk** [wojtekmaj/enzyme-adapter-react-17#51]
```
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.0-0" from @wojtekmaj/enzyme-adapter-react-17@0.6.7
npm ERR!   node_modules/@wojtekmaj/enzyme-adapter-react-17
npm ERR!     dev @wojtekmaj/enzyme-adapter-react-17@"^0.6.7" from the root project
```

```
$ node --version
v18.0.0
$ npm --version
8.6.0
```

My guess is that this is happening due to the `-0` on `^17.0.0-0`. Can that be dropped?

**Comment by wojtekmaj** [comment]
That should be a perfectly valid version as per [NPM's own tooling](https://semver.npmjs.com/).

![obraz](https://user-images.githubusercontent.com/5426427/182120790-4253d553-dc64-40a9-a8d7-77dbaced37f4.png)
