### ISSUE TITLE
method mount() can't used in typescript

### ISSUE THREAD

**Issue by ferryal** [wojtekmaj/enzyme-adapter-react-17#52]
got some issue like this, I try to set mount to global but still facing this issue.

define type global 
`declare global {
    function mount(): () => void
}`

setupTest.ts
<img width="429" alt="Screen Shot 2022-08-09 at 09 36 16" src="https://user-images.githubusercontent.com/12185769/183551292-456f8388-44e8-4ece-ade6-322afc9bb5d5.png">

<img width="619" alt="Screen Shot 2022-08-09 at 09 29 59" src="https://user-images.githubusercontent.com/12185769/183550559-daffb045-fe03-428e-8f90-67cfe2a81660.png">

**Comment by wojtekmaj** [comment]
You assigned mount to global object correctly, that's not your problem.

My best guess is that you installed Jest 28, which no longer uses jsdom test environment as the default.
