### ISSUE TITLE
Cannot install with npm 7.0.15

### ISSUE THREAD

**Issue by netosym** [wojtekmaj/enzyme-adapter-react-17#7]
I recently updated to **node v15.4.0** and **npm 7.0.15**. 
Then, I tried to install the adapter, but it threw me this error:
![image](https://user-images.githubusercontent.com/53659559/102028235-27056680-3d77-11eb-98c1-d82982b1474b.png)

**Comment by wojtekmaj** [comment]
NPM 7 needs the `--legacy-peer-deps` flag when installing `@wojtekmaj/enzyme-adapter-react-17`.

**Comment by netosym** [comment]
Thanks! 😃

**Comment by dreamsparkx** [comment]
Thanks

**Comment by destroyer22719** [comment]
Thanks! This helped me!

**Comment by wojtekmaj** [comment]
Fixed in 0.6.0. You don't need any workarounds anymore.
